apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: self-hosted-runners
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: gusLopezC/K8s-Argo-Actions-API_Python
